models.py
from datetime import datetime

from exts import db


class EmailCaptchaModel(db.Model):
    __tablename__ = "email_captcha"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(100), nullable=False, unique=True)
    captcha = db.Column(db.String(10), nullable=False)
    create_time = db.Column(db.DateTime, nullable=False, default=datetime.now)


class UserModel(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(100), nullable=False, unique=True)
    join_time = db.Column(db.DateTime,default=datetime.now)

blueprints/forms.py
import wtforms
from wtforms.validators import length,email,EqualTo

from models import EmailCaptchaModel, UserModel


class RegisterForm(wtforms.Form):
    username = wtforms.StringField(validators=[length(min=6,max=15)])
    email = wtforms.StringField(validators=[length(min=6,max=35)])
    captcha = wtforms.StringField(validators=[length(min=4,max=4)])
    password = wtforms.StringField(validators=[length(min=6,max=15)])
    repassword = wtforms.StringField(validators=[EqualTo("password")])

    def validate_email(self, field):
        email = field.data

        user_model = UserModel.query.filter_by(email=email).first()
        if user_model:
            raise wtforms.ValidationError("user exist")


    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if not captcha_model or captcha_model.captcha.lower() != captcha.lower():
            raise wtforms.ValidationError("captcha error")

app.py
import config
from flask import Flask
from exts import db,mail
from blueprints import qa_blueprint, user_blueprint
from flask_migrate import Migrate
app = Flask(__name__)
app.config.from_object(config)
db.init_app(app)
mail.init_app(app)
migrate = Migrate(app,db)
app.register_blueprint(qa_blueprint)
app.register_blueprint(user_blueprint)

if __name__ == '__main__':
    app.run()

blueprints/__init__.py
from .qa import bp as qa_blueprint
from .user import bp as user_blueprint

blueprints/qa.py
from flask import Blueprint, render_template

bp = Blueprint("qa", __name__, url_prefix="/")


@bp.route("/")
def index():
    return render_template("index.html")

blueprints/user.py
import random
import string
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for
from flask_mail import Message
from exts import mail, db
from models import EmailCaptchaModel, UserModel
from .forms import RegisterForm


bp = Blueprint("user",__name__,url_prefix="/user")

@bp.route("/login")
def login():
    return render_template("login.html")



@bp.route("/register",methods=['GET','POST'])
def register():
    if request.method == "POST":
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email,username=username,password=password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))

    return render_template("register.html")


@bp.route("/captcha")
def send_mail():
    email = request.args.get("email")
    if not email:
        return 'error'

    base_str = string.ascii_letters + string.digits
    code = ''.join(random.sample(base_str,4))
    message = Message(
        subject="【小胖工具箱】注册验证码",
        recipients=['2625112940@qq.com'],
        body=f"【小胖工具箱】您的注册验证码为:{code},请不要把验证码告诉任何人！"
    )
    mail.send(message)
    captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
    if captcha_model:
        captcha_model.captcha = code
        captcha_model.create_time = datetime.now()
    else:
        captcha_model = EmailCaptchaModel(email=email,captcha = code)
        db.session.add(captcha_model)
    db.session.commit()
    return 'success'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了问答 -  {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for("static",filename="bootstrap/bootstrap.min.css") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="css/init.css") }}">

    {% block head %}   {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('qa.index') }}">知了问答</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {#           导航#}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('qa.index') }}">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('qa.index') }}">发布问答</a>
                </li>
                <li class="nav-item ml-2">
                    <form class="form-inline my-2 my-lg-0 ">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="关键词">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>

            </ul>
            {#           登录注册#}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("user.login") }}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("user.register") }}">注册</a>
                </li>


            </ul>
        </div>
    </div>

</nav>


    <div class="container">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}


{% block title %}首页{% endblock %}

{% block body %}



{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block head %}

{% endblock %}

{% block title %}登录{% endblock %}

{% block body %}

<div class="row mt-2">
    <div class="col-sm">
    </div>
    <div class="col-sm">

        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">邮箱</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用途</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
{#            <div class="form-group form-check">#}
{#                <input type="checkbox" class="form-check-input" id="exampleCheck1">#}
{#                <label class="form-check-label" for="exampleCheck1">立即登录</label>#}
{#            </div>#}
            <button type="submit" class="btn btn-primary btn-block">登录</button>
        </form>




    </div>
    <div class="col-sm">
    </div>
</div>




{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block head %}

{% endblock %}

{% block title %}注册{% endblock %}

{% block body %}

    <div class="row mt-2">
        <div class="col-sm">
        </div>
        <div class="col-sm">

            <form method="post" action="{{ url_for('user.register') }}">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用途</small>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input name="captcha" type="text" class="form-control" aria-describedby="emailHelp">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button">获取验证码</button>
                        </div>
                    </div>

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input name="username" class="form-control" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input name="password" type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input name="repassword" type="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary btn-block">注册</button>
            </form>




        </div>
        <div class="col-sm">
        </div>
    </div>
{% endblock %}